#!/bin/bash
cmake -S ${PWD} -B $1  \
-D NETCDF_C_HEADERS_DIR=${CONDA_PREFIX}/include \
-D NETCDF_CXX_HEADERS_DIR=${CONDA_PREFIX}/include \
-D NETCDF_C_SHARED_LIB_DIR=${CONDA_PREFIX}/lib \
-D NETCDF_CXX_SHARED_LIB_DIR=${CONDA_PREFIX}/lib \
-D LIBCONFIG_C_HEADERS_DIR=${CONDA_PREFIX}/include \
-D LIBCONFIG_CXX_HEADERS_DIR=${CONDA_PREFIX}/include \
-D LIBCONFIG_C_LIB_DIR=${CONDA_PREFIX}/lib \
-D LIBCONFIG_CXX_LIB_DIR=${CONDA_PREFIX}/lib \
-DCMAKE_VERBOSE_MAKEFILE=ON
cmake --build $1