#!/bin/bash
cmake -S ${PWD} -B $1 -G Ninja \
-D NETCDF_C_HEADERS_DIR=${CONDA_PREFIX}/include \
-D NETCDF_CXX_HEADERS_DIR=${CONDA_PREFIX}/include \
-D NETCDF_C_SHARED_LIB_DIR=${CONDA_PREFIX}/lib \
-D NETCDF_CXX_SHARED_LIB_DIR=${CONDA_PREFIX}/lib \
-D LIBCONFIG_C_HEADERS_DIR=${CONDA_PREFIX}/include \
-D LIBCONFIG_CXX_HEADERS_DIR=${CONDA_PREFIX}/include \
-D LIBCONFIG_C_LIB_DIR=${CONDA_PREFIX}/lib \
-D LIBCONFIG_CXX_LIB_DIR=${CONDA_PREFIX}/lib

cmake --build $1