export LIBCONFIGPP_INCLUDE_DIR=/opt/local/include
export PATH=$PATH:/Users/tyounkin/Code/libconfigBuild/include
export THRUST_INCLUDE_DIRS=/Users/tyounkin/Code/thrust/include
export PATH=/usr/local/Cellar/netcdf/4.6.1_1/:$PATH
export  NETCDF_DIR=/Users/tyounkin/Code/netcdfFinal/netcdfCbuild/usr/local
export  NETCDFCXX_DIR=/Users/tyounkin/Code/netcdfFinal/netcdfCxxBuild
export  NETCDFDIR=$NETCDF_DIR/lib
export  NETCDFCXX4DIR=$NETCDFCXX_DIR/lib
export  NETCDFINCLUDE=$NETCDF_DIR/include
export  NETCDFCXX4INCLUDE=$NETCDFCXX4_DIR/include
export  NETCDFLIB=$NETCDFDIR/libnetcdf.dylib
export  NETCDFLIB_CPP=$NETCDFCXX4DIR/libnetcdf_c++4.dylib
export Boost_DIR=/usr/local/Cellar/boost/1.67.0_1
#-DNETCDF_CXX_INCLUDE_DIR=$NETCDFCXX4INCLUDE
#-DNETCDF_CXX_LIBRARY=$NETCDFLIB_CPP
#-DNETCDF_DIR=$NETCDF_DIR
#-DNETCDF_INCLUDE_DIR=$NETCDFINCLUDE
#-DNETCDF_LIBRARY=$NETCDFLIB
