export LIBCONFIGPP_INCLUDE=/usr/local/include #/Users/tyounkin/Code/libconfigBuild/include
#export PATH=$PATH:/Users/tyounkin/Code/libconfigBuild/include
export THRUST_INCLUDE_DIRS=/Users/tyounkin/Code/thrust/include
export THRUST_DIR=/Users/tyounkin/code/thrust/
export PATH=/usr/local/Cellar/netcdf/4.6.1_1/:$PATH
export  NETCDF_DIR=/opt/local #/Users/tyounkin/Code/netcdfFinal/netcdfCbuild/usr/local
export  NETCDFCXX_DIR=/opt/local #/Users/tyounkin/Code/netcdfFinal/netcdfCxxBuild
export  NETCDFDIR=$NETCDF_DIR/lib
export  NETCDFCXX4DIR=$NETCDFCXX_DIR/lib
export  NETCDFINCLUDE=$NETCDF_DIR/include
export  NETCDFCXX4INCLUDE=$NETCDFCXX4_DIR/include
export  NETCDFLIB=$NETCDFDIR/libnetcdf.dylib
export  NETCDFLIB_CPP=$NETCDFCXX4DIR/libnetcdf_c++4.dylib
#export Boost_DIR=/usr/local/Cellar/boost/1.67.0_1/
#export Boost_INCLUDE_DIR=/usr/local/Cellar/boost/1.67.0_1/include
export Boost_DIR=/opt/local/lib #/Users/tyounkin/Code/boostBuild
export Boost_INCLUDE_DIR=/opt/local/include #/Users/tyounkin/Code/boostBuild/include
export PYTHONPATH=/Users/tyounkin/Code/gitr2/python:$PYTHONPATH
#export PYTHONPATH=/Users/tyounkin/Code/numpyBuild-1.14.3/lib.macosx-10.12-x86_64-2.7/:$PYTHONPATH
#export PYTHONPATH=$PYTHONPATH:/Users/tyounkin/Code/python2/lib/python2.7/site-packages
#export PYTHONPATH=$PYTHONPATH:/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy
#export PYTHONPATH=$PYTHONPATH:/Library/Python/2.7/site-packages/scipy-1.0.0.dev0+d6eb2d0-py2.7-macosx-10.12-intel.egg
