#!/bin/bash
source ../environment_files/env.fusiont5.sh

# Link it to the dependencies in an out-of-source build of GITR_fork
cmake -DTHRUST_INCLUDE_DIRS=/home/dg6/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.4.0/cuda-10.2.89-hzby2dvk7t7hh4tbqtx66uexreoc2ih3/include \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_CXX_COMPILER=g++ \
    -DTHRUST_INCLUDE_DIR=/home/dg6/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.4.0/cuda-10.2.89-hzby2dvk7t7hh4tbqtx66uexreoc2ih3/include \
    -DNETCDF_DIR=$NETCDF \
    -DNETCDF_CXX_ROOT=$NETCDFCXX4 \
    -DNETCDF_LIBRARIES=/home/5n4/build/external/netcdf-c-install/lib/libnetcdf.so \
    -DNETCDF_INCLUDE_DIRS=/home/5n4/build/external/netcdf-c/include \
    -DNETCDF_CXX_INCLUDE_DIR=/home/5n4/build/external/netcdf-cxx4-install/include \
    -DNETCDF_CXX_LIBRARY=/home/5n4/build/external/netcdf-cxx4-install/lib/libnetcdf-cxx4.so\
    -DNETCDF_INCLUDE_DIR=/home/5n4/build/external/netcdf-c-install/include \
    -DNETCDF_LIBRARY=/home/5n4/build/external/netcdf-c-install/lib/libnetcdf.so \
    -DNETCDF_CXX_LIBRARY=/home/5n4/build/external/netcdf-cxx4-install/lib/libnetcdf-cxx4.so \
    -DLIBCONFIGPP_LIBRARY=/home/5n4/build/external/libconfig_install/lib/libconfig++.so \
    -DLIBCONFIGPP_INCLUDE_DIR=/home/5n4/build/external/libconfig_install/include \
    -DMPI_C_LIBRARIES=/home/dg6/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.4.0/openmpi-3.1.5-s4r4ogvq4koshpy62bjvslz7bu33upxu/lib/libmpi.so \
    -DMPI_lib_LIBRARY=/home/dg6/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.4.0/openmpi-3.1.5-s4r4ogvq4koshpy62bjvslz7bu33upxu/lib/libmpi.so \
    -DUSE_CUDA=1 \
    -DUSE_MPI=0 \
    -DUSEIONIZATION=1 \
    -DUSERECOMBINATION=1 \
    -DUSEPERPDIFFUSION=1 \
    -DUSECOULOMBCOLLISIONS=1 \
    -DUSEFRICTION=1 \
    -DUSEANGLESCATTERING=1 \
    -DUSEHEATING=1 \
    -DUSETHERMALFORCE=0 \
    -DUSESURFACEMODEL=1 \
    -DUSESHEATHEFIELD=1 \
    -DUSE_SURFACE_POTENTIAL=1 \
    -DBIASED_SURFACE=0 \
    -DUSEPRESHEATHEFIELD=0 \
    -DBFIELD_INTERP=2 \
    -DLC_INTERP=0 \
    -DGENERATE_LC=0 \
    -DEFIELD_INTERP=0 \
    -DPRESHEATH_INTERP=0 \
    -DDENSITY_INTERP=2 \
    -DTEMP_INTERP=2 \
    -DFLOWV_INTERP=0 \
    -DGRADT_INTERP=0 \
    -DODEINT=0 \
    -DFIXEDSEEDS=0 \
    -DPARTICLESEEDS=1 \
    -DGEOM_TRACE=0 \
    -DGEOM_HASH=1 \
    -DGEOM_HASH_SHEATH=1 \
    -DPARTICLE_TRACKS=0 \
    -DPARTICLE_SOURCE_SPACE=0 \
    -DPARTICLE_SOURCE_ENERGY=0 \
    -DPARTICLE_SOURCE_ANGLE=0 \
    -DPARTICLE_SOURCE_FILE=1 \
    -DSPECTROSCOPY=3 \
    -DUSE3DTETGEOM=1 \
    -DUSECYLSYMM=1 \
    -DUSEFIELDALIGNEDVALUES=0 \
    -DFLUX_EA=1 \
    -DFORCE_EVAL=0 \
    -DUSE_SORT=0 \
    -DUSE_DOUBLE=1 \
    -DCHECK_COMPATIBILITY=1 \
    ..
    #-DCMAKE_CXX_FLAGS="-g -Wall -Wextra -Wpedantic -Wconversion -Wno-unused-parameter -Wno-float-conversion -Wno-unused-variable -Wno-unused-but-set-variable" \
    #-DCUDA_TOOLKIT_ROOT_DIR=/home/tqd/Code/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.4.0/cuda-10.1.243-3udvpzzzgaceuczzxile7rnz2limxwe6 \
