# syntax=docker/dockerfile:1

from nvidia/cuda:11.8.0-devel-ubuntu20.04 as stage_1

run echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

run apt-get install -y -q

run apt update

from stage_1 as stage_2

run apt update
run apt install -y git
run apt install -y libhdf5-dev
run apt install -y libnetcdf-dev
run apt install -y libnetcdf-c++4-dev

from stage_2 as stage_3

run apt install ninja-build
run apt install -y vim
run apt install -y libconfig-dev
run apt install -y libconfig++-dev

from stage_3 as stage_4

# the only thing left to install is CLI11 and CMake
run DEBIAN_FRONTEND=noninteractive apt install -y gpg wget

from stage_4 as stage_5

# do all the package adding keys etc
run wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null

run echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null

run apt update

run rm /usr/share/keyrings/kitware-archive-keyring.gpg

run apt install kitware-archive-keyring

run DEBIAN_FRONTEND=noninteractive apt install -y cmake

from stage_5 as stage_6

# acquire python and venv
run apt install -y python3-venv

# copy over the requirements file and 
copy containers/requirements.txt .

# next you need to pip install: matplotlib, numpy, netCDF4, something else

run python3 -m venv /venv

ENV PATH="/venv/bin:$PATH"

run python3 -m  pip install -r requirements.txt

# as a final step volume map the host directory
volume /host

run apt install -y gdb
