# This is an attempt to install GITR on different base images
from alpine:latest

run apk add --update alpine-sdk
run apk add --update cmake
run apk add --update hdf5-dev
run apk add --update netcdf-dev
run apk add --update netcdf-cxx4-dev
run apk add --update catch2-3 --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
run apk add --update libconfig-dev
run apk add --update gdb
run apk add --update ninja
#cli11
#I think that's it... and we need GITR itself too... should we just install it now...

# what do I need next?

# make sure this works then add libconfig, cli-11, and 

# we may even be able to get catch on alpine... would that not be sick...

volume /host

# final build stage will add an entrypoint for a non-interactive container

