%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/timmyyo/GitHub/gimp/matlab/dat.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/19 14:40:59

%% Initialize variables.
filename = '/Users/timmyyo/GitHub/gimp/matlab/dat.txt';
delimiter = ' ';
startRow = [3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65];
endRow = [3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65];

%% Format string for each line of text:
%   column1: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    dataArray{1} = [dataArray{1};dataArrayBlock{1}];
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dat = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID block dataArrayBlock dataArray ans;

xMinV = dat(1);
xMaxV = dat(2);
yMin = dat(3);
yMax = dat(4);
zMin = dat(5); 
zMax= dat(6);
nY = dat(7);%Number of surface cells
nZ = dat(8);
nXv = dat(9);
nYv = dat(10);
nZv = dat(11);

sheathPotential = dat(12);
sheathWidth = dat(13);
Bfieldx_dat = dat(14);
Bfieldy_dat = dat(15); 
Bfieldz_dat= dat(16);
maxDensity = dat(17);
densitySOLDecayLength = dat(18);

maxTemp_eV = dat(19);
tempSOLDecayLength = dat(20);
Dperp_dat= dat(21);
nP= dat(22);
x_dat= dat(23);
y_dat= dat(24);
z_dat= dat(25);
Ex_dat= dat(26);
Ey_dat= dat(27);
Ez_dat= dat(28);

clearvars dat;