
COMP   = mpicxx

SRC_PATH= src
OUT_PATH= bin
OBJ_PATH= obj
INC_PATH= include

PROG = GITR
 
compile: 
	$(COMP) $(FLAGs) -I$(INC_PATH) $(SRC_PATH)/*.cpp  -o $(OUT_PATH)/$(PROG).x 

clean: 
	rm $(OUT_PATH)/* $(OBJ_PATH)/* $(OUT_PATH)/*	

