/* This file is processed by CMake */
#define CONFIG_INTERFACE_UNIT_TEST_FILE "/home/tqd/Code/GITR/build/test_data/test_config.cfg"
#define COULOMB_UNIT_TEST_FILE "/home/tqd/Code/GITR/build/test_data/test_coulomb.cfg"
#define FIELD_UNIT_TEST_FILE_0 "/home/tqd/Code/GITR/build/test_data/ionize.cfg"
#define FIELD_UNIT_TEST_FILE_1 "/home/tqd/Code/GITR/build/test_data/ionize1.cfg"
#define CROSS_FIELD_GEOM_FILE "/home/tqd/Code/GITR/build/test_data/cross_field_geometry.cfg"
#define BORIS_TEST_FILE "/home/tqd/Code/GITR/build/test_data/boris_config.cfg"
#define DATA_TYPES_TEST_FILE "/home/tqd/Code/GITR/build/test_data/file.cfg"
#define GEOM_TEST_FILE "/home/tqd/Code/GITR/build/test_data/geom_test.cfg"
#define FLAT_LINE_TEST_FILE "/home/tqd/Code/GITR/build/test_data/flat_line.cfg"
#define POSITIVE_SLOPE_TEST_FILE "/home/tqd/Code/GITR/build/test_data/positive_slope.cfg"
#define ADAS_TEST_FILE "/home/tqd/Code/GITR/build/test_data/ADAS_Rates_W.nc"
