#!/bin/bash
#
#PBS -l walltime=48:00:00
#PBS -l nodes=2:ppn=4
#PBS -j oe
#PBS -e log.error
#PBS -o log.ouput
#PBS -N gitrBE_PSE
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M tyounkin@utk.edu
cd $PBS_O_WORKDIR
#export OMP_NUM_THREADS=24
source ${HOME}/gitr/env.gpufusion.sh
#mpirun -n 2 -ppn 1 ${HOME}/gitr/build/GITR -i gitrInput750.cfg > log.running
mpirun -n 8 -ppn 4 ${HOME}/gitr/build/GITR -nGPUPerNode 4 -i gitrInput50.cfg > log.running
