COMP = CC 

#libconfig
LIBCONFIG_PATH:=/home/tyounkin/code/libconfig/gnu
INCLUDEFLAGS+=-I${LIBCONFIG_PATH}/include
LIBS+=-L${LIBCONFIG_PATH}/lib -lconfig++

#netcdf
INCLUDEFLAGS+=-I${NETCDF_DIR}/include
LIBS+=-L${NETCDF_DIR}/lib -lnetcdf_c++4 -lnetcdf

#boost
 
