if( USE_CUDA )
  add_compile_definitions( THRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA )
  enable_language( CUDA )
  find_package(CUDA REQUIRED)
  set(CUDA_SEPARABLE_COMPILATION TRUE)
  set(CUDA_HOST_COMPILER ${CMAKE_CXX_COMPILER})
else()
  add_compile_definitions( THRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP )
endif()
