if( USE_CUDA )
  add_compile_definitions( THRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA )
  set( CMAKE_CUDA_COMPILER /home/dg6/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.4.0/cuda-10.2.89-hzby2dvk7t7hh4tbqtx66uexreoc2ih3/bin/nvcc )
  enable_language( CUDA )
  include( FindCUDAToolkit )
  set(CUDA_SEPARABLE_COMPILATION TRUE)
  set(CUDA_HOST_COMPILER ${CMAKE_CXX_COMPILER})
  include_directories( ${CUDAToolkit_INCLUDE_DIRS} )
else()
  add_compile_definitions( THRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP )
endif()
