name: GITR CI
on: push
jobs:
  clone_dependencies:

    runs-on: ubuntu-20.04

    name: clone dependencies
    
    outputs :
      netcdf_library : ${{ steps.clone_netcdf_repo.outputs.netcdf_library }}

    steps:
    - id : clone_netcdf_repo
      name : clone_netcdf_repo
      uses : actions/checkout@v2
      with : 
        repository : Unidata/netcdf-c
        path : netcdf-c
        token : ${{ secrets.PUBLIC_ACCESS }}
    - id : build_install_netcdf_repo
      run : |
        echo "::set-output name=netcdf_library::${GITHUB_WORKSPACE}"
        pushd ${GITHUB_WORKSPACE}/netcdf-c
        mkdir build
        pushd build
        cmake -DENABLE_DAP=OFF
        make -j
        make install

  build_gitr:
    runs-on: ubuntu-20.04
    name: build gitr
    needs : clone_dependencies
    steps:
    - id : output_location
      run : |
        echo Captain! netcdf location: ${{ needs.clone_dependencies.outputs.netcdf_library }}
        
    - id : call_checkoutv2
      uses: actions/checkout@v2
    - id : build_gitr_action
      name: build_gitr_action
      uses: stonecoldhughes/gitr_ci_action@master
