# This file defines the CI build step for GITR
# Captain! Embed the action in the repo instead of having it be a public one
# Captain! Cache the steps to make it run faster. This can be tested.
name: GITR CI
on: push
jobs:
  ahoy_captain_job:
    runs-on: ubuntu-20.04
    name: try to build
    steps:
    - name : clone_gitr_repo
      uses: actions/checkout@v2
    - name: build_gitr_action
      uses: stonecoldhughes/gitr_ci_action@master
