name : Build GITR

on :
  workflow_dispatch :

  push :

    branches :
      - 'dev'
      - 'main'

  pull_request :

    branches :
      - 'main'

env :

  BUILD_TYPE : Debug

jobs :

  build :

    runs-on : ubuntu-latest

    steps :

    - uses : actions/checkout@v2

      with :
        ref : main
        
    - name : Install system dependencies

      run : |
        sudo apt-get install -y libhdf5-dev
        
    - name : Configure CMake

      run : |
        cmake -B ${{github.workspace}}/build -DGITR_USE_CUDA=0 -DGITR_USE_MPI=0

    - name : Build

      run : |
        cmake --build ${{github.workspace}}/build -- -j

    - name : Test

      run : |
        cd ${{github.workspace}}/build
        ctest
