name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-dependency
    - run: sudo apt-get -y install libnetcdf-dev
    - run: dpkg -L libnetcdf-dev
    - run: wget https://github.com/Unidata/netcdf-cxx4/archive/v4.3.1.tar.gz
    - run: tar -xvzf v4.3.1.tar.gz
    - run: ls
    - run: mkdir netcdfcxxbuild
    - run: h5cc -showconfig
    - run: dpkg -L libhdf5-dev
    - run: export CPPFLAGS="-I/usr/include/hdf5/serial"
    - run: export CFLAGS="-I/usr/include/hdf5/serial"
    - run: mkdir netcdf-cxx4-4.3.1/build && cd netcdf-cxx4-4.3.1/build && cmake -DCMAKE_CPP_FLAGS=-I/usr/include/hdf5/serial -DCMAKE_C_FLAGS=-I/usr/include/hdf5/serial -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/netcdfcxxbuild .. && make VERBOSE=1 && ctest && make install
    - run: git clone https://github.com/thrust/thrust.git
    - run: dpkg -L libnetcdf-dev
    - run: export NETCDF_DIR_LIB=$GITHUB_WORKSPACE/netcdfcxxbuild/lib
    - run: export NETCDF_DIR_INC=$GITHUB_WORKSPACE/netcdfcxxbuild/include
    - run: ls netcdfcxxbuild
    - run: ls netcdfcxxbuild/lib
    - run: ls netcdfcxxbuild/include
    - run: ls netcdfcxxbuild/bin
    - run: echo $NETCDF_DIR_LIB
    - run: echo $NETCDF_DIR_INC
    - run: sudo apt-get -y install libconfig++-dev
    - run: dpkg -L libconfig++-dev
    - run: >
        cd build && 
        cmake 
        -DCMAKE_CPP_FLAGS=-I$GITHUB_WORKSPACE/netcdfcxxbuild/include
        -DTHRUST_INCLUDE_DIR=$GITHUB_WORKSPACE/thrust
        -DNETCDF_CXX_INCLUDE_DIR=$GITHUB_WORKSPACE/netcdfcxxbuild/include
        -DNETCDF_CXX_LIBRARY=$GITHUB_WORKSPACE/netcdfcxxbuild/lib/libnetcdf-cxx4.so
        -DNETCDF_LIBRARIES=$NETCDF_DIR_LIB/libnetcdf.dylib
        -DNETCDF_INCLUDE_DIRS=$NETCDF_DIR_INC
        -DLIBCONFIGPP_INCLUDE_DIR=/usr/include
        -DUSE_CUDA=0
        -DUSE_MPI=0
        -DUSEIONIZATION=0
        -DUSERECOMBINATION=0
        -DUSEPERPDIFFUSION=0
        -DUSECOULOMBCOLLISIONS=1
        -DUSEFRICTION=1
        -DUSEANGLESCATTERING=1
        -DUSEHEATING=1
        -DUSETHERMALFORCE=0
        -DUSESURFACEMODEL=0
        -DUSESHEATHEFIELD=0
        -DBIASED_SURFACE=0
        -DUSEPRESHEATHEFIELD=0
        -DBFIELD_INTERP=2
        -DLC_INTERP=0
        -DGENERATE_LC=0
        -DEFIELD_INTERP=0
        -DPRESHEATH_INTERP=0
        -DDENSITY_INTERP=0
        -DTEMP_INTERP=0
        -DFLOWV_INTERP=0
        -DGRADT_INTERP=0
        -DODEINT=0
        -DFIXEDSEEDS=1
        -DPARTICLESEEDS=1
        -DGEOM_TRACE=0
        -DGEOM_HASH=0
        -DGEOM_HASH_SHEATH=0
        -DPARTICLE_TRACKS=1
        -DPARTICLE_SOURCE_SPACE=0
        -DPARTICLE_SOURCE_ENERGY=0
        -DPARTICLE_SOURCE_ANGLE=0
        -DPARTICLE_SOURCE_FILE=0
        -DSPECTROSCOPY=2
        -DUSE3DTETGEOM=0
        -DUSECYLSYMM=1
        -DUSEFIELDALIGNEDVALUES=0
        -DFLUX_EA=0
        -DFORCE_EVAL=0
        -DUSE_SORT=0
        -DCHECK_COMPATIBILITY=1
        .. &&
        make VERBOSE=1 &&
        ctest
    - run: ls build  
      env:
        MY_NAME: "Tim"
