name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-dependency
    - run: sudo apt-get -y install libnetcdf-dev
    - run: wget https://github.com/Unidata/netcdf-cxx4/archive/v4.3.1.tar.gz
    - run: tar -xvzf v4.3.1.tar.gz
    - run: ls 
    - run: git clone https://github.com/thrust/thrust.git
    - run: dpkg -L libnetcdf-dev
    - run: export NETCDF_DIR_LIB=$(eval nc-config --libdir)
    - run: export NETCDF_DIR_INC=$(eval nc-config --includedir)
    - run: cd build && cmake -DTHRUST_INCLUDE_DIR=$GITHUB_WORKSPACE/thrust -DNETCDF_LIBRARIES=$NETCDF_DIR_LIB -DNETCDF_INCLUDE_DIRS=$NETCDF_DIR_INC ..
      env:
        MY_NAME: "Tim"

